### ISSUE TITLE
Title Bar - Add Version #

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#11]
I'd like the Title Bar to also display what version is running.

Example:
7th Heaven - Version 1.56

**Comment by TurBoss** [comment]
this should be easy

**Comment by TurBoss** [comment]
Ok I managed to get the assembly version but is shown as 1.5.6.0

should look like : 7thHeaven Version 1.5.6.0

fine?

**Comment by EQ2Alyza** [comment]
Yep, that's good enough. Can transition the official name, from now on, to match the assembly version name.
