### ISSUE TITLE
Default Entry - Subscriptions Link

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#13]
Can we get the Official Catalog's subscription link added as the default entry whenever users open 7H for the first time? I've seen enough reports of users just opening 7H and going straight to the Catalog tab, then reporting that they can't get anything to show lol

iros://Url/http$pastebin.com/raw.php?i=dDBkYkDu

**Comment by TurBoss** [comment]
now that we have the configs in the apps directory the easiest way to do this is to bundle a preconfigured  catalog.xml

under 7thWorkshop see https://github.com/TurBoss/7h/issues/12

**Comment by TurBoss** [comment]
allready posible
