### ISSUE TITLE
Small Error - First Launch Automatic Settings Detection

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#16]
When you launch 7H for the first time (or whenever the settings.xml is deleted), the automatic detection is making a small error with the Library Path...

Library Path: C:\Games\Steam\steamapps\common\FINAL FANTASY VII\mods/7th Heaven

The final slash is the wrong direction. Simple manual fix, but new users will probably glance right over it without knowing.

**Comment by TurBoss** [comment]
this seems easy to fix
I'll try to get a working version asap

**Comment by TurBoss** [comment]
done

**Comment by EQ2Alyza** [comment]
Another easy fix...

Movies Path: C:\Games\Steam\steamapps\common\FINAL FANTASY VII\data\movies\

Remove the last \ after movies in the automatic detection.

**Comment by TurBoss** [comment]
okay I'll do as son as posible

**Comment by EQ2Alyza** [comment]
Whoops, you responded before I could delete and open a new issue lol

Didn't mean to comment in a closed issue. Just respond with the fix in the new one I opened.

Will close this one now.

**Comment by TurBoss** [comment]
ok Just saw the other issue closing this :D
