### ISSUE TITLE
v1.56 - DebugView Not Working

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#2]
I can no longer get debug reports from DebugView with v1.56. Not a major issue, so for now I will use v1.55 for my debugging.

**Comment by TurBoss** [comment]
what is the debug view?
sry

**Comment by TurBoss** [comment]
Uploaded the debug version

a bit slower but with the debug symbols

https://github.com/TurBoss/7h/releases/tag/1.56

is this what you mean?

**Comment by EQ2Alyza** [comment]
https://technet.microsoft.com/en-us/sysinternals/debugview.aspx

I unfortunately can't use the 7H debug feature when testing compatibility among multiple mods. The log file it saves is usually over 1GB and none of my text editors can open a file that large. I just run that DebugView in the background and can see live report on what's happening. Much easier for me tbh.

**Comment by TurBoss** [comment]
does the debug build do the same?
https://github.com/TurBoss/7h/releases/download/1.56/7H_1.56-Debug.zip

here is a tool to read log files in real time http://tailforwin32.sourceforge.net/

**Comment by TurBoss** [comment]
I found TraceSpy a tool similar to DebugView

I can get the logs if i launch the debug version and launch the game by left clicking on the launch button and select log

**Comment by TurBoss** [comment]
would yo like that the normal release has this feature or can be 2 version normal and debug??

**Comment by EQ2Alyza** [comment]
I'm okay with 2 versions. Would it be harder to maintain 2 versions each time there's an update? I don't expect too many more updates in the future, but it's up to you.

**Comment by TurBoss** [comment]
is the same code just select debug or release on compile time
so I'm closing this

thanks
