### ISSUE TITLE
Images in mod configurations don't display correctly.

### ISSUE THREAD

**Issue by NeonLightning** [TurBoss/7h#21]
![7h display](https://user-images.githubusercontent.com/2992888/42976919-5fe9f978-8b92-11e8-953a-edc60462d76a.png)

**Comment by TurBoss** [comment]
fixed

![imagen](https://user-images.githubusercontent.com/184088/43001528-c8881698-8c25-11e8-81c5-d7a4397a843a.png)

I'll upload it on the next release candidate

Thank you

**Comment by TurBoss** [comment]
available here https://github.com/TurBoss/7h/releases/tag/1.56_RC

**Comment by NeonLightning** [comment]
this still seems off to me. also my cloud one looks nothing like yours so i used yufi again.
![7h display 1](https://user-images.githubusercontent.com/2992888/43027977-1d8dea6c-8c4b-11e8-8c21-c8f82f948b81.png)

**Comment by TurBoss** [comment]
this is what I can see

![imagen](https://user-images.githubusercontent.com/184088/43042295-47c804c2-8d7a-11e8-9b1f-30ec146cf635.png)

what catalog url are you using?

thanks

**Comment by NeonLightning** [comment]
same one everyone suggests
iros://Url/http$pastebin.com/raw.php?i=dDBkYkDu

**Comment by TurBoss** [comment]
yes the same here

I can't figure why is wrong :D

I'm investigating

**Comment by TurBoss** [comment]
inside the iros they are just images 

could you please remove and redownload the mod?
thanks

**Comment by TurBoss** [comment]
Okay I hit the bug by redownloading the mod
:D

**Comment by TurBoss** [comment]
Fixed
https://github.com/TurBoss/7h/releases/download/1.56_RC/7H_1.56_RC6.zip

Thanks

**Comment by NeonLightning** [comment]
seems to be fixed :)

**Comment by TurBoss** [comment]
Thank you
