### ISSUE TITLE
crash on mod activation

### ISSUE THREAD

**Issue by NeonLightning** [TurBoss/7h#23]
setup a fresh install of ff7, converted, setup 7h settings based on the usual guide, installed reunion and menu overhaul, when i click activate it crashed with 

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Iros._7th.Workshop.fLibrary.CheckAllowedActivate(Guid modID) in C:\Users\TurBoss\Projetcs\7h\7thWorkshop\fLibrary.cs:line 564
>    at Iros._7th.Workshop.fLibrary.DoActivate(Guid modID) in C:\Users\TurBoss\Projetcs\7h\7thWorkshop\fLibrary.cs:line 624
>    at Iros._7th.Workshop.fLibrary.ToggleActivateMod(Guid modID) in C:\Users\TurBoss\Projetcs\7h\7thWorkshop\fLibrary.cs:line 864
>    at Iros._7th.Workshop.fLibrary.DoModBarAction(pMod pm, ModBarAction a) in C:\Users\TurBoss\Projetcs\7h\7thWorkshop\fLibrary.cs:line 920
>    at Iros._7th.Workshop.pMod.bActivate_Click(Object sender, EventArgs e) in C:\Users\TurBoss\Projetcs\7h\7thWorkshop\pMod.cs:line 200
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by NeonLightning** [comment]
apparently it was because i hadn't noticed that some of the paths had \\

**Comment by TurBoss** [comment]
what character you do you mean?

"\"

**Comment by NeonLightning** [comment]
no the back slash. the bottom two fields in config both looked like steamapps\\common\\Final\ Fantasy\ VII\ and it had actually tried to install the mods to steamapps\common\final\fantasy\vii\
