### ISSUE TITLE
External iro packer/unpacker

### ISSUE THREAD

**Issue by Kaldarasha** [TurBoss/7h#25]
It would be great to have an external tool to pack or unpack iro files, so I can pack mods through the command line. Ultimately I want use a batch file to automatically create iro files.

**Comment by TurBoss** [comment]
it currently exist
just noticed
ehhee

> Usage: IrosArc [Create|Extract|List|MakePatch|ApplyPatch] [ArchiveFile] (parameters)
> 
> IrosArc Create [ArchiveFile] [BaseFolder] [CompressionType]
>     BaseFolder = folder to pack
>     CompressionType = Nothing|Everything|ByExtension|ByContent
> 
> IrosArc Extract [ArchiveFile] [DestinationFolder] [filter]
>     DestinationFolder = folder to extract into. 
>     Filter = (Optional) Filename(s) to extract.
> 
> IrosArc List [ArchiveFile]
>     Describe contents of archive                 
> 
> IrosArc MakePatch [OriginalArchive] [NewArchive] [PatchFile] [CompressionType]
>     OriginalArchive = original archive you want to make a patch for
>     NewArchive = updated version you want the patch to update to
>     PatchFile = location to save patch into
> 
> IrosArc ApplyPatch [ArchiveFile] [PatchFile]
>     ArchiveFile = Original archive
>     PatchFile = patch to apply
>     Archive is updated IN PLACE. Take a backup copy first if you need to keep the original!

just run

```
 IrosArc.exe Create  [ArchiveFile] [BaseFolder] [CompressionType]
```
in your batch script
