### ISSUE TITLE
Issue: Auto Detect settings completely wrong.

### ISSUE THREAD

**Issue by strife98** [TurBoss/7h#26]
Not sure why this is happening, but on a fresh install of 7th Heaven, using the auto detect settings puts the absolute wrong path for FF7 Exe, Textures Path, and Library Path.

My Exe Path: C:\Games\Final Fantasy VII\FF7.exe
Auto Detect Path: C:\\Games\\Final\ Fantasy\ VII\\FF7.exe

Movies Path is correct.

My Textures Path: C:\Games\Final Fantasy VII\mods\Textures\
Auto Detect Path: C:\\Games\\Final \Fantasy \VII\\mods\Textures\

My Library Path: C:\Games\Final Fantasy VII\mods\7H\
Auto Detect Path: C:\\Games\\Final\ Fantasy\ VII\\mods\7H\

I then redid the Game Converter on the main installation area of FF7 from steam, and the Auto Detect put them in generally the same area except for in the steam folder. 

It looks like 7th doesn't like folder names with spaces and adds \ to each one, it also adds an extra \ to the beginning and end of the main folders for some reason. This seems to be only an issue for 1.56 as it works perfectly fine in 1.55

**Comment by TurBoss** [comment]
I'm trying to fix that issue was discussed on https://github.com/TurBoss/7h/issues/20
so isn't really fixed :(

I'll take a look

thanks!

**Comment by strife98** [comment]
Ah, I didn't know that's what that was. Sorry for opening another section about it.

**Comment by TurBoss** [comment]
no problem you are welcome
