### ISSUE TITLE
.iro unpacker not unpacking whole archive

### ISSUE THREAD

**Issue by demanson** [TurBoss/7h#27]
The rc6 version does not unpack the whole .iro archive on large size iro files.  For example: Field main character models.  7th heaven iro packer/unpacker stops unpacking folders at Red XIII - WolfMan - Red Werewolf + Reasonable Difficulty folder which means all the tifa/sephiroth/vincent and yuffie folders are not unpacked at all not to mention the rest of the red xiii folders.  The stand alone iro packer/unpacker by Kaldarasha unpacks all of them. so I'm fairly certain it isn't the iro itself since I just copied the original file and pasted it into the folder for the iro creator tool and used it to unpack it.

**Comment by TurBoss** [comment]
ok I'll take a look asap

Thanks

**Comment by TurBoss** [comment]
I updated some libraries could you please take a look?

[7H_1.56_RC8.zip](https://github.com/TurBoss/7h/files/3225723/7H_1.56_RC8.zip)
thanks

**Comment by demanson** [comment]
![image](https://user-images.githubusercontent.com/23016791/58526236-4ee4a780-819c-11e9-95f3-15d04024c64d.png)

**Comment by demanson** [comment]
It stops at this point with new one.

**Comment by TurBoss** [comment]
can I have the iro you are using?

**Comment by demanson** [comment]
I'm uploading it to dropbox, I'll send a link when it's done.

**Comment by TurBoss** [comment]
thanks

**Comment by demanson** [comment]
https://www.dropbox.com/sh/hljqnfhndlv8lld/AACeUa8r6V-pdsgt-WXYY6zpa?dl=0

**Comment by TurBoss** [comment]
got it
:)

**Comment by TurBoss** [comment]
Ok I found the issue
System.OutOfMemoryException

lets see how to fix it

it crashes when reache 2 gb ram

**Comment by Kaldarasha** [comment]
I have recently patched the packer file with a 4GB patcher (I usually use cff explorer). It helped with the lgp file unpacker, so I thought it might be good to add it to the unpacker too.

**Comment by Kaldarasha** [comment]
I speaking of the unpacker from iros

**Comment by TurBoss** [comment]
a solution for this could be to split mod tools into another exe

**Comment by TurBoss** [comment]
this seems to be fixed on release candidate 8
https://github.com/TurBoss/7h/releases/download/1.56_RC/7H_1.56_RC8.zip
