### ISSUE TITLE
can we have a nice README?

### ISSUE THREAD

**Issue by TurBoss** [TurBoss/7h#29]
@EQ2Alyza

could you please add some words to the readme?

maybe some cut and paste from the forum?

I just pushed a template

Thanks

**Comment by EQ2Alyza** [comment]
Readme would need to detail each mod within the category, which I don't want to bother my time doing. The best we could do is give each category a Readme that then lists links to each of its mods, but even that takes time to find each mod's link on the forums. I hate busy work =/

**Comment by TurBoss** [comment]
no need for mod details just how to download and setup

or just what this app is for

**Comment by TurBoss** [comment]
done
