### ISSUE TITLE
Workshop -> OpenGL -> Graphics -> Postprocess Drop-Down Menu

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#3]
Can we get this box to instead read the shader options (.post files) from the shader folder and have it display a drop-down menu to choose from? There are a couple new shaders being worked on right now, and I have some older ones from Bootleg I can add as well.

**Comment by TurBoss** [comment]
the way is designed i'm not sure if I can made this to search for the shaders in the directory
the easiest solution for now is to know what are the shaders and add all to the dropdown menu

but i'm interested in discover a way to auto populate the menu

is that what you mean?

**Comment by TurBoss** [comment]
![imagen](https://cloud.githubusercontent.com/assets/184088/22365550/69e3e5aa-e478-11e6-9cb9-dd2170850ed7.png)

**Comment by TurBoss** [comment]
![imagen](https://cloud.githubusercontent.com/assets/184088/22365568/7d31d202-e478-11e6-9c2b-18a3663169f6.png)

**Comment by TurBoss** [comment]
I Can't figure out how to add items to the dropdown menu automatically
the easy way is to modify one xml file

in line 72 is the bloom2 shader
https://github.com/TurBoss/7h/blob/master/7thWorkshop/ConfigSpec-FF7OpenGL.xml#L72

I can simply add more "<option>" lines to the file and it will apear under the dropdown menu

**Comment by EQ2Alyza** [comment]
That's fine. It doesn't need to be automated if I can have the option to edit in new options myself.

Now my next question is if we can have a chosen shader also enable its corresponding frag_source=, vert_source=, and yuv_source=. So for example, I choose the new Sunwalker shader:

<Settings>post_source=shaders/Sunwalker/SmartShaderPost.fx</Settings>

I also want it to enable:

frag_source=shaders/Sunwalker/frag.fx
vert_source=shaders/Sunwalker/vert.fx
yuv_source=shaders/Sunwalker/yuv.fx

Adding Settings tags in the .xml aren't enabling it in the ff7_opengl.cfg.

**Comment by TurBoss** [comment]
this can be specified in the opengl.cfg file?

**Comment by EQ2Alyza** [comment]
Yep.

**Comment by TurBoss** [comment]
hmmmm I'm stuck 🗡 
the opengl setting works diferent from the main program
this will take some time...

**Comment by EQ2Alyza** [comment]
Take your time =)

**Comment by TurBoss** [comment]
Ok I think is done
I'm goin to upload the binaries

**Comment by TurBoss** [comment]
https://github.com/TurBoss/7h/releases/download/1.56/7H_1.56.1-Debug.zip
https://github.com/TurBoss/7h/releases/download/1.56/7H_1.56.1.zip

**Comment by EQ2Alyza** [comment]
Getting a crash when clicking Launch Game.

Crash Message: https://drive.google.com/open?id=0B-Q_AObuWRSXeWs3aWo3VTNHRWc

I edited the ConfigSpec-FF7OpenGL.xml to include all the shader locations I want as options. I'll share that .xml, along with my ff7_opengl.cfg and shaders folder. When I choose a shader option in 7H and click OK, I get the OpenGL Settings Saved message, but the changes are not made in the ff7_opengl.cfg.

ConfigSpec-FF7OpenGL.xml: https://drive.google.com/open?id=0B-Q_AObuWRSXVXpEbWY3cDR5c2c
ff7_opengl.cfg: https://drive.google.com/open?id=0B-Q_AObuWRSXSkg3ZDlZM1ZYQ28
shaders: https://drive.google.com/open?id=0B-Q_AObuWRSXbU12UXF1dUJMb0E

**Comment by TurBoss** [comment]
OK I'm going to take a look

**Comment by TurBoss** [comment]
Some things i notice about opengl parsing

- spaces in options
```
option = value
```
- shaders paths cannot contain spaces :_D but "Text" can
```
   <Option>
      <Text>All - Bloom2</Text>
      <Settings>post_source=shaders/All_Bloom2/bloom2.post</Settings>
      <Frag>frag_source=shaders/All_Bloom2/main.frag</Frag>
      <Vert>vert_source=shaders/All_Bloom2/main.vert</Vert>
      <Yuv>yuv_source=shaders/All_Bloom2/yuv.frag</Yuv>
    </Option>
    <Option>
      <Text>All - Bloom2Dark</Text>
      <Settings>post_source=shaders/All_Bloom2Dark/Bloom2Dark.post</Settings>
      <Frag>frag_source=shaders/All_Bloom2Dark/main.frag</Frag>
      <Vert>vert_source=shaders/All_Bloom2Dark/main.vert</Vert>
      <Yuv>yuv_source=shaders/All_Bloom2Dark/yuv.frag</Yuv>
    </Option>
    <Option>
      <Text>All - Sunwalker</Text>
      <Settings>post_source=shaders/All_Sunwalker/SmartShaderPost.fx</Settings>
      <Frag>frag_source=shaders/All_Sunwalker/frag.fx</Frag>
      <Vert>vert_source=shaders/All_Sunwalker/vert.fx</Vert>
      <Yuv>yuv_source=shaders/All_Sunwalker/yuv.fx</Yuv>
    </Option>
    <Option>
      <Text>ATI - ComplexMultiShader</Text>
      <Settings>post_source=shaders/ATI_ComplexMultiShader/ComplexMultiShader.post</Settings>
      <Frag>frag_source=shaders/ATI_ComplexMultiShader/main.frag</Frag>
      <Vert>vert_source=shaders/ATI_ComplexMultiShader/main.vert</Vert>
      <Yuv>yuv_source=shaders/ATI_ComplexMultiShader/yuv.frag</Yuv>
    </Option>
    <Option>
      <Text>ATI - SmartBloomAdvanced</Text>
      <Settings>post_source=shaders/ATI_SmartBloomAdvanced/SmartBloomAdvanced.post</Settings>
      <Frag>frag_source=shaders/ATI_SmartBloomAdvanced/mainAdvanced.frag</Frag>
      <Vert>vert_source=shaders/ATI_SmartBloomAdvanced/mainAdvanced.vert</Vert>
      <Yuv>yuv_source=shaders/ATI_SmartBloomAdvanced/yuvAdvanced.frag</Yuv>
    </Option>
    <Option>
      <Text>ATI - SmartBloomHDR</Text>
      <Settings>post_source=shaders/ATI_SmartBloomHDR/SmartBloomHDR.post</Settings>
      <Frag>frag_source=shaders/ATI_SmartBloomHDR/mainHDR.frag</Frag>
      <Vert>vert_source=shaders/ATI_SmartBloomHDR/mainHDR.vert</Vert>
      <Yuv>yuv_source=shaders/ATI_SmartBloomHDR/yuvHDR.frag</Yuv>
    </Option>
    <Option>
      <Text>Nvidia - ComplexMultiShader</Text>
      <Settings>post_source=shaders/Nvidia_ComplexMultiShader/ComplexMultiShader.post</Settings>
      <Frag>frag_source=shaders/Nvidia_ComplexMultiShader/main.frag</Frag>
      <Vert>vert_source=shaders/Nvidia_ComplexMultiShader/main.vert</Vert>
      <Yuv>yuv_source=shaders/Nvidia_ComplexMultiShader/yuv.frag</Yuv>
    </Option>
```

```
post_source = shaders/All_Sunwalker/SmartShaderPost.fx
frag_source = shaders/All_Sunwalker/frag.fx
vert_source = shaders/All_Sunwalker/vert.fx
yuv_source = shaders/All_Sunwalker/yuv.fx
```

- post_source, frag_source, vert_source and yuv_source options must exist in openglconfig file first
i'm trying to add it now

**Comment by TurBoss** [comment]
and sorry but I found the correct way to add more settings to a dropdown element
```

  <Setting xsi:type="DropDown">
    <Group>Graphics</Group>
    <Name>Postprocessor</Name>
    <Description>Which postprocessing shader to use</Description>
    <Option>
      <Text>All - Bloom2</Text>
      <Settings>post_source=shaders/All_Bloom2/bloom2.post,frag_source=shaders/All_Bloom2/main.frag,vert_source=shaders/All_Bloom2/main.vert,yuv_source=shaders/All_Bloom2/yuv.frag</Settings>    
    </Option>
    <Option>
      <Text>All - Bloom2Dark</Text>
      <Settings>post_source=shaders/All_Bloom2Dark/Bloom2Dark.post,frag_source=shaders/All_Bloom2Dark/main.frag,vert_source=shaders/All_Bloom2Dark/main.vert,yuv_source=shaders/All_Bloom2Dark/yuv.frag</Settings>    
    </Option>
    <Option>
      <Text>All - Sunwalker</Text>
      <Settings>post_source=shaders/All_Sunwalker/SmartShaderPost.fx,frag_source=shaders/All_Sunwalker/frag.fx,vert_source=shaders/All_Sunwalker/vert.fx,yuv_source=shaders/All_Sunwalker/yuv.fx</Settings>
    </Option>
    <Option>
      <Text>ATI - ComplexMultiShader</Text>
      <Settings>post_source=shaders/ATI_ComplexMultiShader/ComplexMultiShader.post,frag_source=shaders/ATI_ComplexMultiShader/main.frag,vert_source=shaders/ATI_ComplexMultiShader/main.vert,yuv_source=shaders/ATI_ComplexMultiShader/yuv.frag</Settings>
    </Option>
    <Option>
      <Text>ATI - SmartBloomAdvanced</Text>
      <Settings>post_source=shaders/ATI_SmartBloomAdvanced/SmartBloomAdvanced.post,frag_source=shaders/ATI_SmartBloomAdvanced/mainAdvanced.frag,vert_source=shaders/ATI_SmartBloomAdvanced/mainAdvanced.vert,yuv_source=shaders/ATI_SmartBloomAdvanced/yuvAdvanced.frag</Settings>
    </Option>
    <Option>
      <Text>ATI - SmartBloomHDR</Text>
      <Settings>post_source=shaders/ATI_SmartBloomHDR/SmartBloomHDR.post,frag_source=shaders/ATI_SmartBloomHDR/mainHDR.frag,vert_source=shaders/ATI_SmartBloomHDR/mainHDR.vert,yuv_source=shaders/ATI_SmartBloomHDR/yuvHDR.frag</Settings>
    </Option>
    <Option>
      <Text>Nvidia - ComplexMultiShader</Text>
      <Settings>post_source=shaders/Nvidia_ComplexMultiShader/ComplexMultiShader.post,frag_source=shaders/Nvidia_ComplexMultiShader/main.frag,vert_source=shaders/Nvidia_ComplexMultiShader/main.vert,yuv_source=shaders/Nvidia_ComplexMultiShader/yuv.frag</Settings>
    </Option>
```

notice that there are no spaces in options and they are coma separated but the opengl file still need spaces

https://github.com/TurBoss/7h/releases/download/1.56/7H_1.56.2-Debug.zip
https://github.com/TurBoss/7h/releases/download/1.56/7H_1.56.2.zip

**Comment by EQ2Alyza** [comment]
It's saving the ff7_opengl.cfg correctly now. Good work!

But I am still getting a crash when clicking Launch Game.

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at _7thWrapperLib.RuntimeVar.MakeRuntimeVar(String spec, String value)
   at _7thWrapperLib.CRuntimeVar.Init(XmlNode source, LoaderContext ctx)
   at _7thWrapperLib.Conditional.Load(XmlNode source, LoaderContext ctx)
   at _7thWrapperLib.ConditionalFolder..ctor(XmlNode node, LoaderContext ctx)
   at _7thWrapperLib.ModInfo.Load(XmlDocument doc, LoaderContext ctx)
   at _7thWrapperLib.ModInfo..ctor(String filePath, LoaderContext ctx)
   at Iros._7th.Workshop.fLibrary.GetModInfo(InstalledItem ii)
   at Iros._7th.Workshop.fLibrary.SanityCheckCompat()
   at Iros._7th.Workshop.fLibrary.Launch(Boolean varDump, Boolean debug)
   at Iros._7th.Workshop.fLibrary.bLaunch_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by TurBoss** [comment]
I think that there is a typo in the "ConfigSpec-FF7OpenGL.xml"
are you using the one shipped with the binary or a custom one?

**Comment by EQ2Alyza** [comment]
I'm using the one shipped with 1.56.2.

**Comment by TurBoss** [comment]
can you paste your ff7_opengl.cfg http://dpaste.com

I only have one mod enabled can you post your profile too?

**Comment by EQ2Alyza** [comment]
http://dpaste.com/29EMD3Y

**Comment by TurBoss** [comment]
Ok i hit the error while activating "Dynamic Cloud weapons"
so 1.55 can load this mod without any problems
so it has to be my fault but why? 😃

**Comment by EQ2Alyza** [comment]
Uh oh! I hope that's not too difficult to figure out.

**Comment by TurBoss** [comment]
Okay found the problem
Var PPV without ":2" per example fails

so i'm goint to force 2 if PPV does not specify the size

do you aprove?

**Comment by EQ2Alyza** [comment]
Can you give an example to help me understand?

**Comment by TurBoss** [comment]
so dynamic weapons uses the player progress variable PPV (AKA bank2 var 0) 
to hide the Cloud's weapon from 1119 to 1188 of the game progress variable the PPV
```
<Conditional Folder="Event\CloudSwordless" >
	<RuntimeVar Var="PPV" Values="1119..1188" />
</Conditional>
```
the 7thHeaven searchs for Var="PPV:2" the size of the variable 2 bytes

the "2" is missing in the  mod PPV is allways 2 bytes from 0 to 65535
the game only uses from 0 to 1999

but for a unknown reason this missing 2 is breaking...

so i'm goin to make it allways "2" if Var is "PPV"

notice that this bug was allways pressent in my fork (duno why, maybe the libraries update) and  not related to the shaders changes

**Comment by EQ2Alyza** [comment]
Alrighty, I approve.

**Comment by TurBoss** [comment]
ok i'm goin to make some test and i'll upload it

**Comment by TurBoss** [comment]
the tests didn't go fine
now the game can be launched but crash inmediatly

traceSpy gived me the error but i don't know how to fix

I noticed tha the original code from where i started also has this "feature"
so it must be fixed and i don't know why 1.55 binaries work if they match the code

**Comment by TurBoss** [comment]
okay i found the bug!
a missing file in the source tree
7thHeaven.var
I will add and upload again

**Comment by TurBoss** [comment]
https://github.com/TurBoss/7h/releases/tag/1.56
so if it works just close the issue

Thanks

**Comment by TurBoss** [comment]
Thanks
