### ISSUE TITLE
Need a better way to dump vars

### ISSUE THREAD

**Issue by Kaldarasha** [TurBoss/7h#30]
7H can actually dump vars but as far as I do remember it, 7h needs another tool to monitor them. It would be good if 7H would dump a log file with info of the field id and the vars of that field.

**Comment by EQ2Alyza** [comment]
I second this. It would help a lot with the process for making conditional folders.

**Comment by TurBoss** [comment]
I did a small tool I'm trying to integrate it with 7h debug launch
[TurBoLog.zip](https://github.com/TurBoss/7h/files/3457733/TurBoLog.zip)

**Comment by TurBoss** [comment]
a quick soultion is add it to the also launch text area under general settings

**Comment by TurBoss** [comment]
okay release candidate 9 has this feature :)

https://github.com/TurBoss/7h/releases
