### ISSUE TITLE
Unable to run the game with 7h in windows 10 with latest updates

### ISSUE THREAD

**Issue by TurBoss** [TurBoss/7h#37]
I get this error while launching the game from 7h

![imagen](https://user-images.githubusercontent.com/184088/61573322-dc61bb00-aaac-11e9-83f8-b94cff4707d9.png)

any ideas?

Thanks

**Comment by EQ2Alyza** [comment]
Others had this issue and resolved it by running 7H in 640x480 compatibility. Not sure I call this a good resolution though. Why does it suddenly have to run that way to work? Why are some having this issue, but others not?

http://forums.qhimm.com/index.php?topic=19094.0

**Comment by TurBoss** [comment]
https://github.com/EasyHook/EasyHook/issues/295

I fixed by seting ff7.exe to 640x480 

I'll investigate this more

**Comment by TurBoss** [comment]
since this is the only workarround I'll close this issue

Thanks!

**Comment by TurBoss** [comment]
this is related to a windows new feature that requires signing key from microsoft

it can be disable is something related to patch guard

**Comment by TurBoss** [comment]
Ilyaki was able toworkarround this issue

> 
> 
> In my case adding WaitForInputIdle to the process creation fixed the error.
> 
> ```cs
> string directoryPath = Path.GetDirectoryName(exePath);
> 
> STARTUPINFO startup = new STARTUPINFO();
> startup.cb = Marshal.SizeOf(startup);
> startup.dwFlags = 0x1;//STARTF_USESHOWWINDOW
> startup.wShowWindow = 1;//SW_SHOWNORMAL
> 
> bool success = CreateProcess(exePath, "", IntPtr.Zero, IntPtr.Zero, false,
> 	0x00000004, //Suspended
> 	IntPtr.Zero, directoryPath, ref startup, out PROCESS_INFORMATION processInformation);
> 
> if (!success) return -1;
> 
> ResumeThread(processInformation.hThread);
> 
> //Inject can crash without waiting for process to initialise
> WaitForInputIdle(processInformation.hProcess, 0xFFFFFFFF);
> 
> SuspendThread(processInformation.hThread);
> 
> int injectResult = Environment.Is64BitProcess ? 
> 	Injector64.RhInjectLibrary((uint)processInformation.dwProcessId, 0, 0, "", hookDllPath, ptr, (uint)size) : 
> 	Injector32.RhInjectLibrary((uint)processInformation.dwProcessId, 0, 0, hookDllPath, "", ptr, (uint)size);
> 			
> ResumeThread(processInformation.hThread);```
> ```

@julianxhokaxhiu if you could take a look that would be awesome

https://github.com/TurBoss/7h/blob/master/7thWorkshop/fLibrary.cs#L1290
Thanks
