### ISSUE TITLE
Workshop -> OpenGL -> Rendering

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#4]
Could you put in a Bool option for turning off/on direct mode?

direct_mode = off
direct_mode = on

**Comment by TurBoss** [comment]
sure

**Comment by TurBoss** [comment]
Okay its done

I had to resize the options window to make the new option fit
please check if everything its ok
https://github.com/TurBoss/7h/releases/tag/1.56.1

**Comment by EQ2Alyza** [comment]
Works, good job =)
