### ISSUE TITLE
Workshop -> Settings -> Extra Folders

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#5]
Can we get the direct and music folders from the FF7 root folder read by default, rather than having to add them into the Extra Folders window?

I want them read by default the same way that 7H reads other folders, e.g. flevel, flevel.lgp, battle, battle.lgp, etc.

**Comment by TurBoss** [comment]
Something like this?
![7h_direct_music](https://cloud.githubusercontent.com/assets/184088/22471632/3b350c76-e7d3-11e6-94aa-5ae954de0aee.png)


or hidden?

**Comment by EQ2Alyza** [comment]
Hidden. Right now, if you make a mod and throw the files into folders like flevel.lgp, battle.lgp, etc., then they get injected without an Extra Folders or path assigned. I would like the same for music and direct.

The music folder has its subfolder music\vgmstream, and the direct folder has many subfolders (e.g. battle, field, etc.). Open it to see all its subfolders yourself.

**Comment by TurBoss** [comment]
so if i understand 
you want that the directories direct and music be selected by default as "extra folders"?

**Comment by TurBoss** [comment]
please let me know if this is what you want

https://github.com/TurBoss/7h/releases/tag/1.56.2

**Comment by TurBoss** [comment]
this are the changes:
https://github.com/TurBoss/7h/commit/771a4cdce8453216598d886fe6a37eaa37047249

**Comment by EQ2Alyza** [comment]
Will look at it tomorrow and let you know. Too busy/tired to stay up tonight.

EDIT: Working. Thank you!

**Comment by TurBoss** [comment]
Thanks
