### ISSUE TITLE
Readme Button

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#6]
I would like to remove the Readme Button in the Library tab. It's not a very good feature because the text format in the new window is too difficult to write a proper Readme.

I would suggest we change the mod Link: to Readme: to have it look like this...

Author:
Version:
Readme:
*Description*

Now, the Readme: can be linked to a Google Docs Page, which has much better formatting tools to write a proper Readme.

What do you think?

**Comment by TurBoss** [comment]
I'll try a diferent way

leave the readme button where it is and make that button read a separated file eg: readme.md
markdown wich can be writen with the ghostwriter it allows to format the text with headers cursive links etc...

so write readmes would be very easy

https://github.com/wereturtle/ghostwriter/releases

**Comment by TurBoss** [comment]
![imagen](https://cloud.githubusercontent.com/assets/184088/22609235/b29eff4e-ea60-11e6-9c49-302b6a7a5cc6.png)

**Comment by TurBoss** [comment]
![imagen](https://cloud.githubusercontent.com/assets/184088/22610028/c50c0458-ea63-11e6-8e52-1d75ccb095c9.png)

**Comment by TurBoss** [comment]
![imagen](https://cloud.githubusercontent.com/assets/184088/22611000/a15823fc-ea68-11e6-87ea-3a8a1106ab19.png)

**Comment by EQ2Alyza** [comment]
Can ghostwriter have preview images in it? Models and Textures are self-explanatory, so no Readme for them. Instead, additional preview files would be nice.

**Comment by TurBoss** [comment]
also gifs but atm only from imgur
![imagen](https://cloud.githubusercontent.com/assets/184088/22613031/173219f0-ea75-11e6-9a1a-fdb42a5643dc.png)

**Comment by EQ2Alyza** [comment]
I use imgur, so that's fine. I want to test this out, so send me a download whenever.

**Comment by TurBoss** [comment]
[Debug.zip](https://github.com/TurBoss/7h/files/751845/Debug.zip)

here is the debug version

**Comment by TurBoss** [comment]
this is how you embed a image in the readme.md

```
![ImageName](http://i.imgur.com/T5FnUAX.gif)
```

**Comment by EQ2Alyza** [comment]
Can links be made to click and open in a browser?

**Comment by TurBoss** [comment]
checking

**Comment by TurBoss** [comment]
Okay its done

📦 [Release.zip](https://github.com/TurBoss/7h/files/752099/Release.zip)
📦 [Debug.zip](https://github.com/TurBoss/7h/files/752100/Debug.zip)

I found a another markdown editor [MarkDown-Edit](https://github.com/mike-ward/Markdown-Edit/releases/tag/v1.32)

also check de [Specs](http://commonmark.org/)
