### ISSUE TITLE
Canary build: Mods don't affect game. "direct" folder has no files (all empty folders)

### ISSUE THREAD

**Issue by Drakonas** [TurBoss/7h#62]
Wondering if the direct folder is supposed to have no files. All the folders inside are empty. None of my mods are loading even though I have followed guides, set "music" and "direct" in the extra folders, and made sure direct mode is on. I have the mods I want activated and have triple checked the load order. The only change in-game I see is that it's loading the vgmstream PS1 OST.

Load order:

    Satsuki's Battle Textures
    NiNoStyle'sModels
    Satsuki's Field Textures
    New Threat
    cmh175 HQ FMV Pack
    cmh175 Avatars
    Enhanced Stock UI
    Kela51 Spell Textures
    Satsuki's World Textures

I have to use Canary build because 1.56 fails to load the game with an error on the latest Windows 10, and Canary included the fix to address this issue.

EDIT: I should mention that the mods/Textures folder is also empty.

I have just tried a full uninstall (deletion of all files and registry) and reinstall, and models and textures still don't replace anything. It seems it is trying to replace things but fails to properly.

**Comment by HitByBricks** [comment]
Also having this issue on my Steam Deck. FFNx screen appears, but besides that no mods are loaded.

**Comment by TurBoss** [comment]
hello 

better try the versions from here

https://github.com/tsunamods-codes/7th-Heaven

 is better maintained :)


thanks
