### ISSUE TITLE
Cancel download doesn't stop the download

### ISSUE THREAD

**Issue by TurBoss** [TurBoss/7h#7]
Right click on a download and cancel does nothing

**Comment by EQ2Alyza** [comment]
I'm pretty sure what it used to do is stop the current download, then move to the next assigned download link. All of them have two hosts 1) Google Drive 2) MEGA. I am going to add a third provider in the next Catalog update to 3.0 --- https://my.sofortcloud.com/

I think the download window needs some work anyways. Perhaps button options to Pause/Resume and Cancel a highlighted mod?

**Comment by EQ2Alyza** [comment]
You still around? It's been quiet this week.

**Comment by TurBoss** [comment]
yes yes xD
but a bit bussy

I have take a look at this but can't figure how to fix....

**Comment by TurBoss** [comment]
Ok i made some changes and seems to be working...
only mega downloads are able to be canceled for now

**Comment by TurBoss** [comment]
Please test this version:

📦 [Debug.zip](https://github.com/TurBoss/7h/files/762195/Debug.zip)
📦 [Release.zip](https://github.com/TurBoss/7h/files/762196/Release.zip)

Thanks

**Comment by EQ2Alyza** [comment]
Only tested 1 download, but it seems ok.

**Comment by TurBoss** [comment]
ok
so i can close this
if google drive or others fail new issue
