### ISSUE TITLE
UI Text Changes (Last update request...I think...)

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#9]
Can we make some changes to the text in the UI? I want to clean it up just a bit. Here are my suggestions:

Workshop
-------------------------------------
- General Settings
- Aali Driver Settings
-------------------------------------
- Update Catalog
-------------------------------------
- IRO Creation Tool
- Chunk Tool
- Catalog Creation Tool
-------------------------------------
- Toggle Downloads Window
-------------------------------------

Here are what they correspond to:

General Settings = Settings
Aali Driver Settings = OpenGL driver configuration
Update Catalog = Check subscriptions now
IRO Creation Tool = Pack/Unpack .iro archives
Chunk Tool = Chunk tool
Catalog Creation Tool = Mod Generator Assistant
Toggle Downloads Window = Show Downloads Window

Just a side note, Show Downloads Window is not working right now. It no longer toggles it open or closed.

**Comment by TurBoss** [comment]
Hi

I have made the changes in menu and also fixed the download show stuff
please take a look https://github.com/TurBoss/7h/releases/tag/1.56.3

**Comment by EQ2Alyza** [comment]
Almost perfect. Can you move Catalog Creation Tool to the bottom? I like to have the list in order of usage, and that tool is used the least imo.

- IRO Creation Tool
- Chunk Tool
- Catalog Creation Tool

Also, the windows that open when you select them need to have their titles changed to the same text. Right now, for example, if you open General Settings, the title of the new window will still say Settings. Same applies to the rest of them.

**Comment by TurBoss** [comment]
okay i'm on it

**Comment by TurBoss** [comment]
done 
can be found here : https://github.com/TurBoss/7h/releases

I also organized the releases, removed all 1.56.X and only left 1.56 and i will update that release, note that is a pre-release

Thanks

**Comment by EQ2Alyza** [comment]
Looks good. These are all pre-releases. I am not going to give this out to the public until we both can confirm a release is ready.

The next changes I would like are within each of the Workshop options. Be careful editing this. I am changing the text AND the order of some of these options. There's a lot of capitalization changes. I'm confident you will get it done =P

General Settings
--------------------------------
- FF7.exe Path:
- Movies Path:
- Textures Path:
- Library Path:
---------------------------------
- Check For 7th Heaven Updates Automatically
- Import Library Folder Mods Automatically
- Activate Newly Installed Mods Automatically
- Keep Older Mod Versions After Updating
- Bypass Compatibility Locks
------------------------------------
Aali Driver Settings
------------------------------------
- Resolution
Aspect Ratio
Window Mode

I want to make Aspect Ratio and Window Mode a drop-down menu instead of a checkbox. They should look like this in the ConfigSpec-FF7OpenGL.xml:

```
<Setting xsi:type="DropDown">
    <Group>Resolution</Group>
    <Name>Window Mode</Name>
    <Description>Choose Fullscreen or Windowed Mode</Description>
    <Option>
        <Text>Windowed</Text>
            <Setting>fullscreen=off</Setting>
    </Option>
    <Option>
        <Text>Fullscreen</Text>
	    <Setting>fullscreen=on</Setting>
    </Option>
</Setting>

<Setting xsi:type="DropDown">
    <Group>Graphics</Group>
    <Name>Aspect Ratio</Name>
    <Description>Choose an option for the original 4:3 aspect ratio.</Description>
    <Option>
        <Text>Stretch to Fill</Text>
	    <Setting>preserve_aspect=off</Setting>
    </Option>
    <Option>
        <Text>Preserve to Fit</Text>
           <Setting>preserve_aspect=on</Setting>
    </Option>  
</Setting>
```
Right now, when I try to make these changes, 7H will crash when opening Aali Driver Settings. Once you  make these changes, I have a new default ConfigSpec-FF7OpenGL.xml that I would like shipped with the release.

IRO Creation Tool
-------------------------------
- Pack IRO
Source Folder:
Save As IRO:
Compress
-> Nothing
-> Everything
-> By Extension
-> By Content

- Unpack IRO
Source IRO:
Output Folder:

- Patch IRO
Original IRO:
New IRO:
Save As IROP:
Compress
-> Nothing
-> Everything
-> By Extension
-> By Content

- Patch IRO (Advanced)
Source Folder:
Save As IROP:
Compress
-> Nothing
-> Everything
-> By Extension
-> By Content

With the Compress feature, can we add a description to the right of it? I would like it to read this:

Nothing: Compress no files.
Everything: Compress all files.
By Extension: Do not compress JPG, PNG, MP3, and OGG files. Compress all else.
By Content: Compress if it saves >10% file size. Do not compress all else.

Chunk Tool
---------------------------
- Select FLEVEL:
- Output Folder:
- Section #:

Can we put a link to the right of the Section #:? It can lead to here for reference: http://wiki.qhimm.com/view/FF7/Field_Module#General_PC_Field_File_Format
Maybe the link text can be **Info**

Catalog Creation Tool
-------------------------------
- Mod File
Link Source:

- Mega Link Generator

**Comment by TurBoss** [comment]
the xml doesn't work because a missing "s" in "settings" under "option"
```
<Setting xsi:type="DropDown">
    <Group>Graphics</Group>
    <Name>Aspect Ratio</Name>
    <Description>Choose an option for the original 4:3 aspect ratio.</Description>
    <Option>
        <Text>Stretch to Fill</Text>
	    <SettingS>preserve_aspect=off</SettingS>
    </Option>
    <Option>
        <Text>Preserve to Fit</Text>
           <SettingS>preserve_aspect=on</SettingS>
    </Option>  
</Setting>
````

**Comment by EQ2Alyza** [comment]
Thanks =) I figured it was something I did. The error message said an element was missing in the xml, but didn't tell me what element or which line to look at.

Are the other changes doable?

**Comment by TurBoss** [comment]
yes give me some time

**Comment by TurBoss** [comment]
- General Setings

- [x] Paths

- [x] Checkboxes

-

- [x] IRO Creation Tool

-

- [x] Chunk tool

-

- [x] Catalog Creation Tool

**Comment by EQ2Alyza** [comment]
Hope all is going well.

For the next release, please make this the new ConfigSpec-FF7OpenGL.xml: https://drive.google.com/file/d/0B-Q_AObuWRSXSEw0NnMwRXNCTDQ/view?usp=sharing

**Comment by TurBoss** [comment]
OpenGL settings is done but not uploaded yet

The checkbox stuff under General Settings is not easy to move... so I'm goin to leave it for now

**Comment by TurBoss** [comment]
something is wrong with the upload i will try later

**Comment by EQ2Alyza** [comment]
That's fine. Don't need to get a headache over it. As long as the text is edited, the placement can stay the same.

**Comment by TurBoss** [comment]
okay here are the latest builds
https://github.com/TurBoss/7h/releases/tag/1.56

**Comment by TurBoss** [comment]
Hello any update about this 

Thanks

**Comment by EQ2Alyza** [comment]
Hi! Please wait another week. I am very busy with work right now. I'll be back soon.

**Comment by EQ2Alyza** [comment]
All seems to be well so far. Were you not able to put the link I requested in the Chunk Tool section and the description next to the Compress feature? It's okay if you aren't capable of doing it, I just want to know if you tried or not.

**Comment by TurBoss** [comment]
Sorry but can't remember let me a day please

Thanks

**Comment by TurBoss** [comment]
well i have some time i can look at this :_D when you say Section # you mean a dropdown menu with the names of the sections?

Thanks

**Comment by TurBoss** [comment]
![chunk_tool](https://cloud.githubusercontent.com/assets/184088/24372446/499071c6-132e-11e7-8b04-c95894152049.png)

this is what i have

**Comment by TurBoss** [comment]
seems that section# can ve a coma separated list of sections

**Comment by TurBoss** [comment]
![chunk tool draft](https://cloud.githubusercontent.com/assets/184088/24373577/13029b30-1332-11e7-9617-ae95ae4bdb3f.png)

This is a Draft do you like it?

**Comment by EQ2Alyza** [comment]
Yes, I think the check boxes are a better idea. If I select multiple boxes, will it chunk all of them with one click of the Extract button?

**Comment by TurBoss** [comment]
yes currently works by entering a coma separated values eg. 1,2,6,7

i'll start working on this

**Comment by TurBoss** [comment]
Hi

I have done the changes now its working (extract all sections based on the selection)

it would be very helpfull if you where able to compile the source to test changes so I don't have to upload builds so often

you may need 
https://www.gitkraken.com/    to get the latest changes of the source
https://www.visualstudio.com/downloads/ the comunity edition to compile the sources

I also include a bat file to make build and packaging more easy

if you have any questions plz join Gitter (there is an app for windows)

Thanks

https://github.com/TurBoss/7h/releases/tag/1.56

**Comment by TurBoss** [comment]
can this be closed?

Thanks

**Comment by TurBoss** [comment]
what is missing here?

Thanks
